project_id = "ttunfxjorklswweacugh"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.chat]
    verify_jwt = false
  [functions.paystack-checkout]
    verify_jwt = false
  [functions.paystack-webhook]
    verify_jwt = false
  [functions.store-checkout]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
